### ISSUE TITLE
Pattern Regex fails

### ISSUE THREAD

**Issue by andrewmartin** [medipass/react-credit-card-input#16]
The browser Regex test on the `pattern` attribute, currently set to `[0-9]*`, fails.

![image](https://user-images.githubusercontent.com/273842/40015391-10f6fd1a-5768-11e8-871f-88488f5855fb.png)

**Comment by jxom** [comment]
Hey @andrewmartin, thanks for raising this. I'll add an 'up for grabs' label on this, and I'll fix it when I find the time. If anyone else wants to raise a PR, that'll be sweet.

**Comment by acoyfellow** [comment]
pattern <code>[0-9 ]+</code> is working for me.

**Comment by acoyfellow** [comment]
I also ran into issues with the EXP field pattern

<code>[0-9a-zA-Z]{2} / [0-9a-zA-Z]{2}</code> fixed it

**Comment by advance512** [comment]
Can you merge this? The issue makes the component unusable

**Comment by jxom** [comment]
Fixed in `1.0.10`.

**Comment by advance512** [comment]
Great. Thank you!
