### ISSUE TITLE
cardNumberInputRenderer is not a function

### ISSUE THREAD

**Issue by sergey-givola** [medipass/react-credit-card-input#17]
By using provided examples there is an exeption thrown

```
index.js:527 Uncaught TypeError: cardNumberInputRenderer is not a function
          at CreditCardInput._this.render (index.js:527)
```

Propper fix for this is to add following properties:

 ```
cardCVCInputRenderer={props => <input {...props} />}
cardExpiryInputRenderer={props => <input {...props} />}
cardNumberInputRenderer={props => <input {...props} />}
```

Seems like such function supposed to be default value but it is not set in the latest version of the lib

**Comment by jxom** [comment]
Hey Sergey.

Looks like you downloaded the canary version of the library (1.0.0-canary.0). I’ll need to fix this so it doesn’t download prereleases from npm. If you wish to use the version in sync with the docs, just download 0.6.0. I’ll be releasing 1.0.0 shortly however. :)

**Comment by jxom** [comment]
This should be fixed in the latest version!
