### ISSUE TITLE
What branch is the demo code on?

### ISSUE THREAD

**Issue by zeckdude** [medipass/react-credit-card-input#21]
Awesome package! Thanks for all your hard work!

I noticed that there is a slight difference in the code that is pulled from `master` versus the demo at https://medipass.github.io/react-credit-card-input. Where is that code located?

I noticed that, in the demo, if you enter any number between 2 and 9 in the expiration field, it will prepend the number with a `0`. Also, when you finish typing the second number, it automatically adds the `/`, which it doesn't do on `master`. 

Can you please provide the code that is being used on the demo?

**Comment by jxom** [comment]
Hey @zeckdude, looks like the demo was on an old version of the code. Both of these issues should be fixed in `1.0.7`.

**Comment by zeckdude** [comment]
@jxom I actually wanted those features for what I’m working on. Having the “0” prepend is a great feature and having the “/“ be added automatically after the second character is typed is desired as well. Are you saying those features were removed after the demo was created? If so, can you please provide me with the commit of when that was removed so I can add that functionality back into my fork?

Thanks a lot!

**Comment by zeckdude** [comment]
I found the commit: https://github.com/medipass/react-credit-card-input/commit/fabf63aed80050b1e458c0b49da4434c81e35b1f

Thanks!

**Comment by jxom** [comment]
I fixed it yesterday, and should be on version `1.0.7`. :)
