### ISSUE TITLE
Upgrade styled-components

### ISSUE THREAD

**Issue by benogle** [medipass/react-credit-card-input#22]
Styled components is at 3.3.3, but this still uses 2.x. If your app uses 3.x, and includes this, there are some crazy results.

Maybe a peer dep would be better?

https://github.com/styled-components/styled-components/issues/1032

**Comment by jxom** [comment]
Hey @benogle,

Thanks for raising this - I didn't know different styled-component versions between the peer and library conflicted. :\ 

I think a solution for the interim would be to just update styled-components to ^3. I don't think adding as a peer dep would be an ideal solution.

**Comment by jxom** [comment]
@benogle, can you install `v1.0.9` and check to see if everything is all good?
