### ISSUE TITLE
Customize labels

### ISSUE THREAD

**Issue by snowcxt** [medipass/react-credit-card-input#25]
Is there a way to the change text, e.g. Card number, Card number is invalid, etc?

**Comment by jxom** [comment]
Hi @snowcxt,

You are able to change placeholder text by using custom renderers https://github.com/medipass/react-credit-card-input/blob/master/readme.md#custom-input-renderer-usage. 

However, there is no way to change error-based help text at the moment. I'll mark this issue as a 'good first issue' if anyone wants to add custom error messages.
