### ISSUE TITLE
More meaningful error messages

### ISSUE THREAD

**Issue by jxom** [medipass/react-credit-card-input#3]
The error messages are pretty generic at the moment. If an input is invalid, it will just display that the input is invalid (e.g. 'Card number is invalid'). Would be nice to have more meaningful error messages such as 'Card number is too short'.

Here are the cases I can think of off the top of my head:

- Card number too short
- Month is not between 1 and 12
- Year is less than the current year

**Comment by teobais** [comment]
The card expiry validation  is based on the [payment](https://github.com/jessepollak/payment) component. Specifically `payment`'s `validateCardExpiry` method returns a `boolean`, which implies that we have to rewrite `payment`'s pieces inside `index.js` of `react-credit-card-input`, if we want to achieve more specific error messages.

I do not consider this a good practice.

Can you think of any better solution?

**Comment by jxom** [comment]
Yeah, I wish payment had more specific validation... However, I think a simple, lightweight module could be written to validate an expiry (date) input.

**Comment by teobais** [comment]
You mean we should also use an additional module so that we can work around this functionality or completely replace the `payment` one? What is your wish?

**Comment by jxom** [comment]
Well we are using `payment` for formatting input fields, and validating card numbers and CVCs... Which I think is fine. I think adding another (lightweight) module to validate date inputs would be sensible.

**Comment by teobais** [comment]
I will have a look at this.

**Comment by teobais** [comment]
Hey, sorry for the late reply, things have been hectic lately.

On topic, as of today, we can play with [`credit-card-expiry-validator`](https://github.com/thodorisbais/credit-card-expiry-validator) to fix this issue.

Before moving forward with a PR that uses `credit-card-expiry-validator`, I would be interested in your input.

**Comment by jxom** [comment]
Hey. 

Don't be sorry, I really appreciate your contribution and input! That library you created looks pretty good. I had a brief look at it before, and one thing I found that may be a bit problematic is that the function always returns a truthy value of either a boolean (true) or a string (the error message). How would you assert whether an error exists? I kind of don't want to type `if (typeof validateExpiry(expiry) === 'string')` to check if an error exists. 
Perhaps the function could be more specific for it's purpose? Such as: `isExpiryInvalid(expiry)` which returns a string if it's invalid, `false` if it is valid.

Let me know your thoughts.

**Comment by teobais** [comment]
Hello,

hahah, indeed, it's not that handy this way.

We will have v0.0.2 before the end of the working week.

**Comment by jxom** [comment]
Would you like me to assign this issue to you?

**Comment by teobais** [comment]
Sure!

**Comment by jxom** [comment]
Thanks! I've marked this issue as 'in progress', if by any chance you don't want to work on this issue anymore, let me know and I'll mark it back to 'help wanted'.

**Comment by teobais** [comment]
@jxom is [this](https://github.com/thodorisbais/credit-card-expiry-validator/blob/more-specific-module-function/index.js) what you want?

**Comment by jxom** [comment]
LGTM ☺️

**Comment by teobais** [comment]
Cool, #11 is now using v0.0.2 and is available for review.

**Comment by jxom** [comment]
Fixed in 0.4.5
