### ISSUE TITLE
Can't type for expiry date

### ISSUE THREAD

**Issue by vongdarakia** [medipass/react-credit-card-input#31]
I'm unable to input anything for the expiry date. The error I'm getting in the console is this:

`TypeError: Cannot read property 'invalidExpiryDate' of undefined`

To fix this issue, I had to add a customTextLabel object with expiryError.

`customTextLabels={{
    expiryError: {}
}}`

But customTextLabel is optional. So this seems like a bug to look into.

**Comment by jxom** [comment]
Thanks! Fixed in `1.0.15`
