### ISSUE TITLE
Why validation error on Amex card no. input ?

### ISSUE THREAD

**Issue by ZenMilan** [medipass/react-credit-card-input#33]
I'm unable to use amex card with this library upon entering amex card no. I get validation error given in attached image:
<img width="625" alt="screenshot 2018-11-01 at 3 27 02 pm" src="https://user-images.githubusercontent.com/35091628/47844485-b004f200-ddea-11e8-9d75-c9e532cb42ed.png">

**Comment by jxom** [comment]
What version of `react-credit-card-input` are you on?

**Comment by ZenMilan** [comment]
Hi @jxom, I got the solution the error pop-up was from chrome, the issue was not with library. Thank you
