### ISSUE TITLE
Chrome dev console warning: Invalid DOM property `maxlength`

### ISSUE THREAD

**Issue by vadimgo** [medipass/react-credit-card-input#48]
Displaying a default CreditCardInput in a react app generates the following warning in the developer console:

index.js:1446 Warning: Invalid DOM property `maxlength`. Did you mean `maxLength`?
    in input (created by CreditCardInput)
    in label (created by Context.Consumer)
    in StyledComponent (created by styled.label)
    in styled.label (created by CreditCardInput)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by CreditCardInput)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (created by CreditCardInput)

**Comment by vadimgo** [comment]
Could you please comment why this issue was closed - is this not a valid issue?

**Comment by jxom** [comment]
Because it's fixed :)

**Comment by vadimgo** [comment]
Ah, great - thank you very much!
