### ISSUE TITLE
Auto-completion support

### ISSUE THREAD

**Issue by schickling** [medipass/react-credit-card-input#7]
Would be great if this library would support auto-fill: https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

**Comment by jxom** [comment]
Hey @schickling, thanks for raising this! I'll mark this as 'up for grabs', and if I have time this week, I'll work on it! :)

**Comment by jxom** [comment]
Fixed in 0.4.2! 1049fa17c384f8de67295c4072faa96c97691178

**Comment by schickling** [comment]
Awesome! Would be great if you could publish on NPM!

**Comment by jxom** [comment]
Whoops, give it another shot @schickling
